name: ic-websocket-sdk-js tests

# only run when a commit is pushed to the main branch
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: ./.github/actions/setup-node

      - name: Run tests
        run: pnpm test
